# schemas.py
from pydantic import BaseModel, ConfigDict
from typing import Optional

class BookBase(BaseModel):
    """
    Shared properties for creating or reading a book.
    """
    title: str
    author: str
    year: Optional[int] = None

class BookCreate(BookBase):
    """
    Properties to receive on book creation (POST/PUT).
    Inherits from BookBase.
    """
    pass

class BookResponse(BookBase):
    """
    Properties to return to the client.
    Includes the 'id' which is generated by the DB.
    """
    id: int

    # Configuration to allow Pydantic to read data from ORM objects
    model_config = ConfigDict(from_attributes=True)